// <auto-generated />
namespace BlogProjectRedeux.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class EditedBlogPosts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditedBlogPosts));
        
        string IMigrationMetadata.Id
        {
            get { return "201407150048230_EditedBlogPosts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
